version: "3.2"
services:
  db:
    restart: always
    image: mongo
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=5000
    ports:
      - "5000:5000"
    networks:
      - db-net

  backend:
    restart: always
    container_name: code
    command : bash -c "python check_db.py --service-name db --ip db --port 27017 && 
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge